<?php 
	print '
	<h1>About Us</h1>
	<h2>F1 - The Business</h2>
	<iframe width="640" height="360" src="https://www.youtube.com/embed/V4Xrp49KXng" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe></div>
	<p>Bernard Charles Ecclestone (born 28 October 1930) is a British business magnate.He is the former chief executive of the Formula One Group, which manages Formula One and controls the commercial rights to the sport, and part-owns Delta Topco, the ultimate parent company of the Formula One Group. As such, he was commonly described in journalism as F1 Supremo.</p>
	<p>On 23 January 2017, it was announced that Ecclestone had been replaced by Chase Carey as chief executive of the Formula One Group, though he has been appointed as chairman emeritus and will act as an adviser to the board.</p>
	<p>His early involvement in the sport was as a competitor and then as a manager of drivers Stuart Lewis-Evans and Jochen Rindt. In 1972, he bought the Brabham team, which he ran for fifteen years.As a team owner he became a member of the Formula One Constructors Association. His control of the sport, which grew from his pioneering the sale of television rights in the late 1970s, was chiefly financial, but under the terms of the Concorde Agreement he and his companies also managed the administration, setup and logistics of each Formula One Grand Prix, making him one of the richest men in the UK. Ecclestone entered two Grand Prix races as a driver, during the 1958 season, but failed to qualify for either of them.</p>
	<p>Immediately after the end of World War II, Ecclestone went into business trading in spare parts for motorcycles, and formed the Compton & Ecclestone motorcycle dealership with Fred Compton. His first racing experience came in 1949 in the 500cc Formula 3 Series, acquiring a Cooper Mk V in 1951. He drove only a limited number of races, mainly at his local circuit, Brands Hatch, but achieved a number of good placings and an occasional win.He initially retired from racing following several accidents at Brands Hatch, intending to focus on his business interests.</p>
	<p>After his accident, Ecclestone temporarily left racing to make a number of eventually lucrative investments in real estate and loan financing and to manage the Weekend Car Auctions firm. He returned to racing in 1957 as manager of driver Stuart Lewis-Evans, and purchased two chassis from the disbanded Connaught F1 team,whose driver line-up over the years had included Lewis-Evans, Roy Salvadori, Archie Scott Brown, and Ivor Bueb. Ecclestone even attempted, unsuccessfully, to qualify a car himself at Monaco in 1958 (although this has since been described as "not a serious attempt"). He also entered the British Grand Prix, but the car was raced by Jack Fairman.He continued to manage Lewis-Evans when he moved to the Vanwall team; Salvadori moved on to manage the Cooper team. Lewis-Evans suffered severe burns when his engine exploded at the 1958 Moroccan Grand Prix and succumbed to his injuries six days later; Ecclestone was rather shaken up and once again retired from racing..</p>
	';
?>